### ISSUE TITLE
关于API无法在Purpur1.20.1版本兼容运行的问题

### ISSUE THREAD

**Issue by AssassinOWL** [koca2000/NoteBlockAPI#103]
[06:04:06 INFO]: [Shhxmusic] Enabling Shhxmusic v1.0-SNAPSHOT
[06:04:06 ERROR]: Error occurred while enabling Shhxmusic v1.0-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: com/xxmicloxx/NoteBlockAPI/songplayer/SongPlayer
at org.virtuous.shhxmusic.main.shhxmusic.Shhxmusic.onEnable(Shhxmusic.java:24) ~[Shhxmusic-1.0-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.1.jar:git-Purpur-2017]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.1.jar:git-Purpur-2017]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.1.jar:git-Purpur-2017]
at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:564) ~[purpur-1.20.1.jar:git-Purpur-2017]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.20.1.jar:git-Purpur-2017]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440) ~[purpur-1.20.1.jar:git-Purpur-2017]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.1.jar:git-Purpur-2017]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.20.1.jar:git-Purpur-2017]
at net.minecraft.server.MinecraftServer.lambda����spin0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2017]
at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.xxmicloxx.NoteBlockAPI.songplayer.SongPlayer
at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:142) ~[purpur-1.20.1.jar:git-Purpur-2017]
at io.papermc.paper.plugin.entrypoint.classloader.PaperPlug

我在服务器中安装了这个插件 但是依然没有运行

**Comment by CSneko** [comment]
这里是github,且原作者可能不会中文，请使用英语提问

**Comment by koca2000** [comment]
I indeed don't know Chinese and it would be better to communicate in English. According to Google Translator you added the NoteBlockAPI.jar to your plugins directory. Is that right? Are you the developer of the Shhxmusic plugin? Have you also added NoteBlockAPI to your plugin.yml as depend or softdepend?

**Comment by koca2000** [comment]
Closing for inactivity
