### ISSUE TITLE
Not block api throwing null on entitysongplayer

### ISSUE THREAD

**Issue by abhiram555** [koca2000/NoteBlockAPI#58]
NoteBlockAPI is throwing null on 1.16 server

org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[server.jar:git-Spigot-379750e-43c7ff9]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server.jar:git-Spigot-379750e-43c7ff9]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[server.jar:git-Spigot-379750e-43c7ff9]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[server.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2186) ~[server.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:32) ~[server.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[server.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[server.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[server.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(SourceFile:144) ~[server.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[server.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(SourceFile:118) ~[server.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:941) ~[server.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:934) ~[server.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[server.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:918) ~[server.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:850) ~[server.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[server.jar:git-Spigot-379750e-43c7ff9]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.NullPointerException
at com.abhiram.smartphone.api.NoteBlockAPI.songplayer.SongPlayer.start(SongPlayer.java:290) ~[?:?]
at com.abhiram.smartphone.api.NoteBlockAPI.songplayer.SongPlayer.(SongPlayer.java:97) ~[?:?]
at com.abhiram.smartphone.api.NoteBlockAPI.songplayer.SongPlayer.(SongPlayer.java:74) ~[?:?]
at com.abhiram.smartphone.api.NoteBlockAPI.songplayer.SongPlayer.(SongPlayer.java:58) ~[?:?]
at com.abhiram.smartphone.api.NoteBlockAPI.songplayer.RangeSongPlayer.(RangeSongPlayer.java:22) ~[?:?]
at com.abhiram.smartphone.api.NoteBlockAPI.songplayer.EntitySongPlayer.(EntitySongPlayer.java:17) ~[?:?]
at com.abhiram.smartphone.listeners.GuiListener.onPlayerInventoryInteract(GuiListener.java:43) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[server.jar:git-Spigot-379750e-43c7ff9]
... 18 more

**Comment by koca2000** [comment]
Caused by embedding into another plugin.
